In [2]:
import sys
import uuid
from pathlib import Path
import pandas as pd
import json
import os

In [26]:
dev_responses = []

for root, dirs, files in os.walk('./meps/gemini_gemini/chartqapro/test'):
     for file in files:
        with open(os.path.join(root, file), "r") as auto:
            mep = json.loads(auto.read())
            dev_responses.append({
                'id': mep['sample']['sample_id'],
                'question': mep['sample']['question'],
                'planner_answerable': mep['plan']['parsed']['answerability_check'],
                'analyst_answer': mep['analyst']['parsed']['answer'],
                'verifier_answer': mep['verifier']['parsed']['answer'],
                'verifier_correct': mep['verifier']['parsed']['verdict']
            })

In [27]:
pd.DataFrame(dev_responses)

,id,question,planner_answerable,analyst_answer,verifier_answer,verifier_correct
0,AAPL/2014/page_38.pdf-3,what was the change in amount of long term deb...,answerable,$ 28987,$ 28987,confirmed
1,AAPL/2008/page_78.pdf-2,what was the average change in unrealized gain...,answerable,$ 5,$ 5,confirmed
2,AAPL/2004/page_36.pdf-2,what was the gross margin decline in fiscal 20...,answerable,0.2%,0.2%,confirmed
3,PM/2014/page_67.pdf-2,what was the total of euro notes issued in 201...,answerable,$3098 million,$3098 million,confirmed
4,PM/2015/page_38.pdf-1,what is the percentage change in the weighted-...,answerable,8.86%,8.86%,confirmed
...,...,...,...,...,...,...
195,PKG/2009/page_65.pdf-4,what percentage of total purchase commitments ...,answerable,56.20%,56.20%,confirmed
196,STT/2008/page_83.pdf-2,what percent higher is the average var for for...,answerable,63.64%,63.64%,confirmed
197,STT/2009/page_73.pdf-1,what was the percentage change in the amortize...,answerable,23.12%,23.12%,confirmed
198,STT/2011/page_83.pdf-1,in 2011 what was the amount of tax related to ...,answerable,$114 million,$114 million,confirmed
199,STZ/2006/page_68.pdf-2,what were the remaining mondovi net assets acq...,answerable,871861,871861,confirmed

In [29]:
df_dev = pd.read_json("./FinQA_dataset/dev.json")
df_dev['question'] = df_dev['qa'].apply(lambda x: x['question'])
df_dev['answer'] = df_dev['qa'].apply(lambda x: x['answer'])

In [30]:
df_dev_meps = pd.merge(df_dev[['question', 'answer', 'id']], pd.DataFrame(dev_responses), on=['question', 'id'], how='inner')

In [31]:
df_dev_meps

,question,answer,id,planner_answerable,analyst_answer,verifier_answer,verifier_correct
0,what is the average payment volume per transac...,127.40,V/2008/page_17.pdf-1,answerable,127.4,127.4,confirmed
1,what was the percentage cumulative total retur...,93.5%,C/2017/page_328.pdf-1,answerable,93.5%,93.5%,confirmed
2,what percentage of the total oil and gas mmboe...,24.69%,DVN/2007/page_58.pdf-2,answerable,24.69%,24.69%,confirmed
3,in 2010 what was the net change in net revenue...,18.6,ETR/2011/page_341.pdf-3,answerable,18.6,18.6,confirmed
4,what are the deferred fuel cost revisions as a...,60.3%,ETR/2004/page_213.pdf-2,unanswerable,UNANSWERABLE,60.3%,revised
...,...,...,...,...,...,...,...
195,in 2019 what was the percent of the total futu...,10.7%,GIS/2019/page_37.pdf-2,answerable,10.67%,10.66%,revised
196,"for fiscal 2018 , what percentage of the total...",0,ADBE/2018/page_86.pdf-2,answerable,2.49%,UNANSWERABLE,revised
197,what was the percent of the debt maturities ou...,72.1%,DRE/2013/page_39.pdf-2,answerable,72.09%,74.14%,revised
198,what is the anticipated percentage increase in...,42.9%,UNP/2006/page_37.pdf-2,answerable,42.73%,42.73%,confirmed
199,in 2006 what was the percent of the total inve...,66.3%,UNP/2006/page_37.pdf-1,answerable,66.32%,66.32%,confirmed